title: Data Techbook
author: Data Coaches
copyright: Multiverse, 2021
logo: logo.png

execute:
  execute_notebooks: 'off'

parse:
  myst_extended_syntax: true
  myst_enable_extensions:
    # https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # https://github.com/executablebooks/jupyter-book/blob/c923bdbfb178d3da478394d6149a7754034ed6fb/docs/_config.yml
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

launch_buttons:
  notebook_interface: "classic"  # or "jupyterlab"
  thebe                  : true

html:
  favicon: multi-logo.png
  navbar_footer_text: Visit our <a href="https://www.multiverse.io/en-GB">main
    website</a>

  use_repository_button: false       
  use_issues_button: false           


repository:
  url: https://github.com/DataFellowship/book                        
  path_to_book: .                  
  branch: main

